# Generated by Django 4.2.30 on 2026-06-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0028_add_reminder_only_to_pokemonmove"),
        ("pokemon_v2", "0028_pokemonevolution_evolved_form_and_more"),
    ]

    operations = []
