# Generated by Django 4.2.30 on 2026-09-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_v2", "0029_merge_20260626_1447"),
        ("pokemon_v2", "0036_pokemonevolution_condition_expression_and_more"),
    ]

    operations = []
